---
inherit: ../ea-base-manifest.yml
applications:
- name: analytic-configurator-<space>
  host: analytic-configurator-<space>
  services:
    - stuf
    - logstash-1
    - bm-apm
  env:
    clientId: <SEC_BMS_EA_SERVICE_CLIENT_ID>
    clientSecret: <SEC_BMS_EA_SERVICE_CLIENT_SECRET>
    acsUri: https://predix-acs.run.asv-pr.ice.predix.io
    apmAssetUrl: https://apm-asset-rc.run.asv-pr.ice.predix.io
    eaAnalyticsUrl: https://analytics-service-<space>.run.asv-pr.ice.predix.io
    NEW_RELIC_APP_NAME: bms-analytic-configurator-<space>
    statetype_default: String
    statevalue_default: RUNNING
    readbefore_downtime_default: 259200
    readbefore_production_default: 259200
    getallassets_downtime_default: false
    getallassets_production_default: false
    prodEvt_triggerTag_default_dataType: String
    prodEvt_triggerTag_default_values: true,false
    prodEvt_triggerTag_suffix: OPER_RUNNING
    prodEvt_nonTiggerTag_suffixAlias: PARTCOUNT,SERIALNUMBER,PARTNUMBER
    lookbehindtimevalue_production_default: 60000
    downtime_nonTriggerTag_suffix:
    downtime_triggerTag_suffix: STATE
    downtime_triggerTag_knownstates: RUNNING,DOWN,FEED_HOLD,IDLE,SETUP,LOADING
    spring_profiles_active: cloud
