---
cloud_provider:
    type: cf
    url: https://api.system.asv-pr.ice.predix.io
    org: Brilliant Manufacturing
    space: Demo
    default_domain: run.asv-pr.ice.predix.io
    self_signed: true
artifact_store:
    type: artifactory
    url: https://devcloud.swcoe.ge.com/artifactory
hooks:
