---
inherit: ../wip-base-manifest.yml
applications:
- name: production-event-parser-prod
  host: production-event-parser-prod
  memory: 4GB
  instances: 2
  services:
    - rabbitmq
    - postgres
    - logstash-1
    - stuf
  env:
    PRODUCTION_EVENT_SERVICE_URL: https://json-production-event-service-prod.run.asv-pr.ice.predix.io
    CLIENT_ID: <SEC_BMS_PROD_EVENT_PARSER_CLIENT_ID>
    CLIENT_SECRET: <SEC_BMS_PROD_EVENT_PARSER_CLIENT_SECRET>
    filestoreConsumeScope: filestore.consume
    ProductionEventIngestScope: productionEvent.ingest
    NEW_RELIC_APP_NAME: bms-production-event-parser-stuf-<space>
    rabbitmq_service_name: rabbitmq
    MEMORY_LIMIT: 2G
